<?php
// Automatically Generated by TestLink Installer - Fri, 08 Sep 23 15:04:59 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.22.5.33:3306');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
